### ISSUE TITLE
composer depoendancies list php-http/client-implementation, not used and does not exist

### ISSUE THREAD

**Issue by thawkins** [jdecool/clockify-api#2]
The composer.json file lists 

php-http/client-implementation which does not seem to be used and does not exist.

**Comment by jdecool** [comment]
Hi @thawkins,

The `php-http/client-implementation` is a virtual package for [HTTPlug](http://httplug.io) library.

As it's describe in the [README](https://github.com/jdecool/clockify-api#install-it), you have to install an implementation when you require `jdecool/clockify-api`.

If you want to use Guzzle, use this command : `composer require jdecool/clockify-api "php-http/guzzle6-adapter:^1.0"`.

**Comment by thawkins** [comment]
You cant install the package with composer, because it says that package
does not exist and hence the package install fails.

**Comment by jdecool** [comment]
Just make a try, it works : 

![image](https://user-images.githubusercontent.com/433926/71991189-006cb080-3235-11ea-9186-0e894fea3d8e.png)

Can you describe how you try to install the library ?

**Comment by thawkins** [comment]
Using the composer dependancies manager in PhpStorm.

**Comment by jdecool** [comment]
I don't know how to use the dependency manager in PhpStorm.

Could you try to install dependencies in command lines with the terminal ?

At the end, this is not a library bug.
