### ISSUE TITLE
update php-http/client-common to ^2.0

### ISSUE THREAD

**Issue by godbout** [jdecool/clockify-api#3]
was trying to do a PR draft but can't find the option?

anyways, would you be willing to bump your php-http/client-common to ^2.0. i'd love to use your package for my Alfred-Time Workflow, but there's a conflict related to the php-http/client-common version. i use the latest one while you use an old one.

if you're ok with bumping up your dependency, then i'll do a PR.

thanks!

**Comment by jdecool** [comment]
Hello @godbout ,

Yes you can do a PR to upgrade `php-http` dependencies :+1:

**Comment by jdecool** [comment]
I close this issue.

It's fixed by #2 

Thanks for your contribution.
