### ISSUE TITLE
How to create a Task on a Project using Laravel?

### ISSUE THREAD

**Issue by vladc-eastwolf** [jdecool/clockify-api#7]
I am trying to build a Laravel App that communicates with Clockify. I figured out looking at the documentation how the get works and I've been able to see all the workspaces, projects and tasks already created but I am struggling trying to create a task for a project from my Laravel App.
This is the store method

```php 
public function store()  { 
    $builder = new ClientBuilder();
    $client = $builder->createClientV1(config('clockify.clockify_api_key'));

    $request = new Task\TaskRequest('',\request('name'),'','','');
    $task = new Task\Task($builder->createClientV1(config('clockify.clockify_api_key')));

    $task->create(\request('workspace'),\request('project'),$request);
    dd($task);
}
```

This is the form 

```html
<form action="{{route('tasks.store',['workspace'=>request('workspace'),'project'=>request('project')])}}" method="POST">
          
    <div class="form-group">
        <input class="form-control" type="text" name="name" placeholder="Task Name">
    </div>

    <div class="form-group">
        <button class="btn btn-primary" type="submit">Create</button>
    </div>
</form>
```

And I am getting 
![image](https://user-images.githubusercontent.com/68373781/99954833-09eb0280-2d8c-11eb-9dd5-a08ab6297ad3.png)

**Comment by jdecool** [comment]
Hi @vladc-eastwolf ,

Dedicated API classes are in alpha stage.
I drunk when I've created thoses classes regards what I've made (because it can't works).

There's a workaround by calling the API directly with the generic HTTP client with a code like this one:

```php
$workspaceId = request('workspace');
$projectId = request('project');

$builder = new ClientBuilder();
$client = $builder->createClientV1(config('clockify.clockify_api_key'));
$data = $client->post("/workspaces/$workspaceId/projects/$projectId/tasks", ['name' => request('name')]);
```

**Comment by jdecool** [comment]
I close this issue because of inactivity.

Feel free to reopen it if needed.
